"""empty message

Revision ID: b69ae1abeaad
Revises: 
Create Date: 2022-04-03 13:51:13.923376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69ae1abeaad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kinds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kinds_id'), 'kinds', ['id'], unique=False)
    op.create_index(op.f('ix_kinds_name'), 'kinds', ['name'], unique=False)
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kind_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kind_id'], ['kinds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeds_id'), 'breeds', ['id'], unique=False)
    op.create_index(op.f('ix_breeds_name'), 'breeds', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breeds_name'), table_name='breeds')
    op.drop_index(op.f('ix_breeds_id'), table_name='breeds')
    op.drop_table('breeds')
    op.drop_index(op.f('ix_kinds_name'), table_name='kinds')
    op.drop_index(op.f('ix_kinds_id'), table_name='kinds')
    op.drop_table('kinds')
    # ### end Alembic commands ###
