"""User datetime columns

Revision ID: e7089c7e300b
Revises: 04e83905898e
Create Date: 2022-04-05 20:29:26.570865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7089c7e300b'
down_revision = '04e83905898e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
