"""Kind table

Revision ID: e914d20f5ac0
Revises: b69ae1abeaad
Create Date: 2022-04-03 13:57:18.905949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e914d20f5ac0'
down_revision = 'b69ae1abeaad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
